using DSA.DataStructures;
using DSA.DataStructures.LinkedList;
using DSA.DataStructures.LinkedList.DoubleLinkedList;
using DSA.DataStructures.Queue;
using DSA.DataStructures.Stack.StackBasedOnArray;
using DSA.DataStructures.Stack.StackBasedOnLinkedList;
using DSA.SortingAlgorithms;


ArrayBasedQueue<int> ints = new ArrayBasedQueue<int>(5);
ints.Enqueue(1);
ints.Enqueue(2);
ints.Enqueue(3);
ints.Enqueue(4);
ints.Enqueue(5);
var item = ints.Front();
Console.WriteLine(item);
item = ints.Front();
Console.WriteLine(item);
item = ints.Front();
Console.WriteLine(item);
item = ints.Front();
Console.WriteLine(item);
item = ints.Front();
Console.WriteLine(item);
item = ints.Front();
Console.WriteLine(item);
item = ints.Front();
Console.WriteLine(item);
item = ints.Front();
Console.WriteLine(item);
item = ints.Front();
Console.WriteLine(item);
item = ints.Front();
Console.WriteLine(item);